### PR TITLE
Suggested updates to the COC section of the README

### PR DESCRIPTION
**Pull request by Scotchester**
Curious to hear thoughts on my proposal to say COCs are required, and if there is anything we can do or suggest that we could do to really enforce that requirement.

### CODE REVIEW

**Review by willbarton — APPROVED** [review]
I agree completely with requiring codes of conduct.

**Comment by tomdyson** [comment]
I'm not sure we can or should mandate COCs. For example, I believe that some members of Four Digits, the Dutch agency who started Wagtail Space and have run three events, have philosophical objections to COCs, on the grounds that the law is the right tool to deal with bad behaviour. I may have misunderstood or misrepresented this, but I don't think this is an uncommon position in countries like the Netherlands whose legal system is based on civil law (including most of continental Europe but not the UK).

**Comment by marteki** [comment]
We also need to think about locations where law does not provide protections in the same way, and might not support the type of behavior that organizers wish to state.

There's also the question of what "bad behavior" is, and how it should be phrased. Maybe rather than trying to make a single statement be one-size-fits-all, we could:

- offer options for how organizers could present recommended/expected behavior,
- state whether they're following under a particular type of civil law, and
- what that actually means for each conference in plain non-legal language?

**Comment by FlipperPA** [comment]
What do you think about saying we "highly recommend" having a clear, enforceable Code of Conduct? It doesn't quite make it a requirement, and the `enforceable` allows breathing room for different countries laws and customs.

**Comment by Scotchester** [comment]
That sounds like a good change to me, @FlipperPA. I've updated the PR accordingly. The first sentence of the section now reads:

"We highly recommend that Wagtail Space events have a clear, enforceable, and publicised code of conduct that seeks to ensure the event is as safe and inclusive for all participants as possible."

**Pull request merged**
